version: '3'
services:
  app:
    build: .
    environment:
      - DISPLAY=:99
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - selenium
  selenium:
    image: selenium/standalone-firefox
    ports:
      - "5900:5900"
      - "4444:4444"
    networks:
      - selenium
networks:
  selenium:
    driver: bridge
