name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Substitua pelo seu AWS region

      - name: Install dependencies and build
        run: |
          # Comandos para instalar dependências, compilar ou qualquer outra preparação necessária
          # Exemplo: pip install -r requirements.txt

      - name: Zip files
        run: |
          zip -r lambda-package.zip . -x "*.git*" "*__pycache__*" "*.github*"
        
      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name NomeDaSuaFuncaoLambda \
            --zip-file fileb://lambda-package.zip
